apiVersion: v1
kind: Pod
metadata:
    name: nginx
spec:
  containers:
  - name: ip-app
    image: harshajain/ip_app:2
    ports:
    - containerPort: 80
    resources:
      requests:
          memory: "100Mi"
          cpu: 400m 
      limits:  
          memory: "250Mi"
          cpu: 1000m
