apiVersion: v1
kind: Pod
metadata:
    name: ip-app-cm
spec:
  containers:
  - name: ip-app
    image: harshajain/ip_app:2
    ports:
    - containerPort: 80
    env:
    - name: DB_USER
      valueFrom:
          secretKeyRef:
              name: my-secret
              key: db_user
    - name: DB_PASSWORD
      valueFrom:
          secretKeyRef:
              name: my-secret
              key: db_pass          
      