apiVersion: v1
kind: Pod
metadata:
    name: nginx-emptydir
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
       - containerPort: 80
    volumeMounts:
    - name: shared-vol
      mountPath: "/var/log/nginx"
  - name: busbox-adaptor
    image: busybox 
    command: ["/bin/sh"]
    args: ["-c", "while true; do ls /var/log/nginx; cat /var/log/nginx/access.log; sleep 5; done"]
    volumeMounts:
    - name: shared-vol
      mountPath: "/var/log/nginx"
  volumes: 
  - name: shared-vol
    emptyDir: {}   
