apiVersion: autoscaling/v2 
kind: VerticalPodAutoscaler 
metadata: 
    name: my-vpa
spec: 
    scaleTargetRef: 
        apiVersion: apps/v1
        kind: Deployment
        name: main-app-with-hpa 
    updatePolicy:
        updateMode: "Auto"
             