apiVersion: v1
kind: Pod
metadata:
    name: nginx-test
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
       - containerPort: 80
---

apiVersion: v1
kind: Pod
metadata:
    name: nginx
spec:
  containers:
  - name: ip-app
    image: harshajain/ip_app:2
    ports:
    - containerPort: 80

