apiVersion: v1
kind: Service 
metadata: 
    name: my-headless-ip-app
spec:
    clusterIP: None     
    selector:
        app: ip-app-sfs
    ports: 
      - name: http 
        port: 30008
        targetPort: 8080
        
        
