apiVersion: batch/v1
kind: CronJob
metadata:
    name: my-job
spec:
    schedule: "* * * * *"
    successfulJobsHistoryLimit: 5
    failedJobsHistoryLimit: 5
    jobTemplate: 
        spec: 
            template:
              spec: 
                containers: 
                - name: busybox 
                  image: busybox
                  command: 
                  - /bin/sh
                  - -c 
                  - "sleep 4"
                restartPolicy: OnFailure 
