apiVersion: apps/v1
kind: Deployment
metadata:
  name: ip-app-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: ip-app
  template:
    metadata:
      labels:
        app: ip-app
    spec:
      tolerations:
      - key: env
        effect: NoSchedule
        operator: "Exists"        
      containers:
      - name: ipapp
        image: harshajain/ip_app:2
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
