apiVersion: v1
kind: Pod
metadata:
    name: sidecar-container
spec:
    containers:
       - name: nginx 
         image: nginx 
         ports:
          - containerPort: 80
       - name: sidecar-busybox
         image: busybox
         command: ["/bin/sh"]
         args: ["-c","sleep 10000"] 
